# Generated by Django 5.1 on 2024-11-08 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mind_palace", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="information",
        ),
        migrations.RemoveField(
            model_name="item",
            name="title",
        ),
        migrations.AlterField(
            model_name="palace",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="palaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Subtopic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="mind_palace.item",
                    ),
                ),
            ],
        ),
    ]
