# Generated by Django 5.1 on 2024-11-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mind_palace", "0002_remove_item_information_remove_item_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
